# Generated by Django 3.1.14 on 2022-02-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220127_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(help_text='Reference to Student model', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
