# Generated by Django 3.1.14 on 2022-02-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220219_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(help_text='Reference to Student model', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
